update
upgrade

install zsh
install git
install w3m
install phantomjs
install redis
install mongodb
install wget
install tig
install zsh
install tree
install the_silver_searcher
install postgresql
install openssl
install rbenv
install ruby-build
install tmux
install go
install mysql

cleanup
